export const KEYBOARD_TYPE_QWERTY = "KEYBOARD_TYPE_QWERTY";
export const KEYBOARD_TYPE_CHEATAKEY = "KEYBOARD_TYPE_CHEATAKEY";
export const TEST_TYPE_1ST = "TEST_TYPE_1ST";
export const TEST_TYPE_2ND = "TEST_TYPE_2ND";
export const TEST_TYPE_PRACTICE = "TEST_TYPE_PRACTICE";
