export const TEST_TYPE_CTK_DIRECTION = "TEST_TYPE_CTK_DIRECTION";
export const TEST_TYPE_CTK_VOWEL_KEY_TYPE = "TEST_TYPE_CTK_VOWEL_KEY_TYPE";

export const KEYBOARD_TYPE_QWERTY = "KEYBOARD_TYPE_QWERTY";
export const KEYBOARD_TYPE_CHEATAKEY = "KEYBOARD_TYPE_CHEATAKEY";
export const KEYBOARD_TYPE_GBOARD = "KEYBOARD_TYPE_GBOARD";

export const REPORT_TYPE_SUBMIT = "REPORT_TYPE_SUBMIT";
export const REPORT_TYPE_ERROR_TYPO = "REPORT_TYPE_ERROR_TYPO";

export const TEST_TYPE_PART_B_QWERTY = "TEST_TYPE_PART_B_QWERTY";
export const TEST_TYPE_PART_B_GBOARD = "TEST_TYPE_PART_B_GBOARD";
export const TEST_TYPE_PART_C_CHEATAKEY = "TEST_TYPE_PART_C_CHEATAKEY";
export const TEST_TYPE_PART_D_CHEATAKEY = "TEST_TYPE_PART_D_CHEATAKEY";
export const TEST_TYPE_PART_E_CHEATAKEY = "TEST_TYPE_PART_E_CHEATAKEY";
export const TEST_TYPE_PART_E_QWERTY_ONEHAND =
  "TEST_TYPE_PART_E_QWERTY_ONEHAND";
export const TEST_TYPE_PART_E_GBOARD_ONEHAND =
  "TEST_TYPE_PART_E_GBOARD_ONEHAND";
export const TEST_TYPE_PART_E_CHEATAKEY_ONEHAND =
  "asdTEST_TYPE_PART_E_CHEATAKEY_ONEHANDf";
