export const KEYBOARD_TYPE_QWERTY = "KEYBOARD_TYPE_QWERTY";
export const KEYBOARD_TYPE_CHEATAKEY = "KEYBOARD_TYPE_CHEATAKEY";
export const TEST_TYPE_QWERTY = "TEST_TYPE_QWERTY";
export const TEST_TYPE_CTK_FIRST = "TEST_TYPE_CTK_FIRST";
export const TEST_TYPE_CTK_PRACTICE = "TEST_TYPE_CTK_PRACTICE";
export const TEST_TYPE_CTK_FINAL = "TEST_TYPE_CTK_FINAL";
