const testSet = [
  "a bad workman finds fault with his tools",
  "a big fish must swim in deep waters",
  "a black hen lays a white egg",
  "a buddy from my old stomping grounds",
  "a door must either be shut or open",
  "a drowning man will catch at a straw a drowning man plucks at a straw",
  "a fool may talk but a wise man speaks",
  "a friend in need is a friend indeed",
  "a good medicine tastes bitter",
  "a journey of a thousand miles begines with a single step",
  "a leopard ca not change his spots",
  "a little knowledge is dangerous",
  "a loaf of bread is better than the song of many birds",
  "a man is known by the company he keeps",
  "a picture is worth a thousand words",
  "a rags to riches story",
  "a rat in a trap",
  "a rolling stone gathers no moss",
  "a sound mind in a sound body",
  "a stitch in time saves nine",
  "adding insult to injury",
  "after the storm comes the calm",
  "as one sows so shall he reap",
  "bad workmen blame their tools",
  "be it ever so humble there iss no place like home",
  "beauty is in the eye of the beholder",
  "better be the head of a dog than the tail of a lion",
  "better late than never",
  "birds of a feather flock together",
  "blood is thicker than water",
  "born is barn",
  "can not get blood from a turnip",
  "cannot see the wood for the trees",
  "casting pearls before swine",
  "charity begins at home",
  "claw me and i will claw thee",
  "cut off your nose to spite your face",
  "dead men tell no tales",
  "do good and do not look back",
  "do into others as you would have them into you",
  "do not count your chickens before they hatch",
  "do not mount a dead horse",
  "easier said than done",
  "empty vessels make the most sound",
  "enter ye in at the strait gate",
  "even a worm will turn",
  "even homer sometimes nods",
  "every cloud has a silver lining",
  "every dog has his day",
  "every jack has his jill",
  "every minute seems like a thousand",
  "every tide has its ebb",
  "everyone has a skeleton in the closet",
  "face the music",
  "failure is but a stepping stone to success",
  "finders keepers loser weepers",
  "fine clothes make the man",
  "fools rush in the where angels fear to tread",
  "genius must be born and never can be taught",
  "get angry at others for ones own mistakes",
  "go home and kick the dog",
  "go it while you are young",
  "greed has no limits",
  "habit is a second nature",
  "haste makes waste",
  "he bit off more than he can chew",
  "he that will steal a pin will steal an ox",
  "heaven helps those who help hemselves",
  "hunger is best sauce",
  "icing on the cake",
  "if at first you do not succeed try try again",
  "if you laugh blessings will come your way",
  "ignorance is bliss",
  "ill news flies",
  "in one ear and out the other",
  "it is a piece of cake",
  "it is not good to listen to flattery",
  "it never rains but it pours",
  "it takes two to tango",
  "kill two birds with one stone",
  "knock at the door and it will be opened",
  "let sleeping dogs lie",
  "lets get to the point",
  "life is full of ups and downs",
  "like father like son",
  "little drops of water make the mighty cean",
  "look before you leap",
  "love me love my dog",
  "many drops make a shower",
  "many hands make light work",
  "marry in haste repent at leisure",
  "match made in heaven",
  "mend the barn after the horse is stolen",
  "money makes the mare to go",
  "more haste less speed",
  "never put off till tomorrow what you can do today",
  "no news is good news",
  "no pains no gains",
  "no smoke without fire",
  "none but the brave deserves the fair",
  "nothing ventured nothing gained",
  "one man sows and another man reaps",
  "one rotten apple spoils the barrel",
  "one swallow does not make a summer",
  "out of sight out of mind",
  "pie in the sky",
  "practice makes perfect",
  "searching for a needle in a haystack",
  "shrouds have no pockets",
  "slow and steady win the game",
  "stabbed in the back",
  "starts off with a bang and ends with a whimper",
  "strike while the iron is hot",
  "talk of the devil and you will hear the flutter of his wings",
  "talking to the wall",
  "the early bird catches the worm",
  "the grass is greener on the other side of the fence",
  "the pot calls the kettle black",
  "the sparrow near a school sings the primer",
  "there is no place like home",
  "thorn in the side",
  "thrown away like an old shoe",
  "time and tide wait for no man",
  "to see is to believe",
  "to teach a fish how to swim",
  "troubles never come singly",
  "turning green with envy",
  "walls have ears",
  "well begun is half done",
  "what is learned in the cradle is carried to the grave",
  "where there is a will there is a way",
  "who holds the purse rules the house",
  "you do not know what you have got until you have lost it",
  "you have cried wolf too many times",
];

module.exports = testSet;
