const testSet = [
  "Greed has no limits",
  "Stabbed in the back",
  "A rolling stone gathers no moss",
  "One man sows and another man reaps",
  "Searching for a needle in a haystack",
  "Do into others as you would have them into you",
  "Finders keepers loser weepers",
  "Be it ever so humble there is no place like home",
  "Seize the day",
  "A rags to riches story",
  "Pie in the sky",
  "One rotten apple spoils the barrel",
  "Get angry at others for ones own mistakes",
  "Do good and do not look back",
  "Time and tide wait for no man",
  "If you laugh blessings will come your way",
  "Talking to the wall",
  "Do not count your chickens before they hatch",
  "Charity begins at home",
  "He bit off more than he can chew",
  "Empty vessels make the most sound",
  "Every dog has his day",
  "Casting pearls before swine",
  "A rat in a trap",
  "Lets get to the point",
  "Habit is a second nature",
  "A leopard can not change his spots",
  "Everyone has a skeleton in the closet",
  "You have cried wolf too many times",
  "In one ear and out the other",
  "A journey of a thousand miles begines with a single step",
  "Pride will have a fail",
  "Mend the barn after the horse is stolen",
  "The grass is greener on the other side of the fence",
  "There is no place like home",
  "Better late than never",
  "He that will steal a pin will steal an ox",
  "Haste makes waste",
  "Marry in haste repent at leisure",
  "Adding insult to injury",
  "After the storm comes the calm",
  "Face the music",
  "None but the brave deserves the fair",
  "A black hen lays a white egg",
  "Can not get blood from a turnip",
  "Shrouds have no pockets",
  "A man is known by the company he keeps",
  "To teach a fish how to swim",
  "Nothing ventured nothing gained",
  "It is not good to listen to flattery",
  "No smoke without fire",
  "Do not mount a dead horse",
  "Starts off with a bang and ends with a whimper",
  "Heaven helps those who help hemselves",
  "Dead men tell no tales",
  "A friend in need is a friend indeed",
  "Born is barn",
  "The sparrow near a school sings the primer",
  "Bad workmen blame their tools",
  "A fool may talk but a wise man speaks",
  "Cannot see the wood for the trees",
  "Ignorance is bliss",
  "No pains no gains",
  "Slow and steady win the game",
  "Troubles never come singly",
  "Thorn in the side",
  "Hunger is best sauce",
  "Who holds the purse rules the house",
  "Will is power",
  "A buddy from my old stomping grounds",
  "Even homer sometimes nods",
  "If at first you do not succeed try try again",
  "A picture is worth a thousand words",
  "Many hands make light work",
  "Never put off till tomorrow what you can do today",
  "Money makes the mare to go",
  "Life is not all beer and skittles",
  "Fools rush in the where angels fear to tread",
  "A bad workman finds fault with his tools",
  "Better be the head of a dog than the tail of a lion",
  "One swallow does not make a summer",
  "Claw me and i will claw thee",
  "A drowning man will catch at a straw a drowning man plucks at a straw",
  "A big fish must swim in deep waters",
  "Walls have ears",
  "Cut off your nose to spite your face",
  "Every tide has its ebb",
  "Practice makes perfect",
  "Every cloud has a silver lining",
  "The pen is mighter than sword",
  "Look before you leap",
  "Let bygones be bygones",
  "You do not know what you have got until you have lost it",
  "A loaf of bread is better than the song of many birds",
  "Love me love my dog",
  "Every jack has his jill",
  "Well begun is half done",
  "A good medicine tastes bitter",
  "Do not cry before you are hurt",
  "The early bird catches the worm",
  "Match made in heaven",
  "Fine clothes make the man",
  "Life is full of ups and downs",
  "Go it while you are young",
  "Genius must be born and never can be taught",
  "Let sleeping dogs lie",
  "Failure is but a stepping stone to success",
  "Beauty is in the eye of the beholder",
  "More haste less speed",
  "A stitch in time saves nine",
  "Little drops of water make the mighty cean",
  "Go home and kick the dog",
  "Turning green with envy",
  "A door must either be shut or open",
  "Kill two birds with one stone",
  "Ill news flies",
  "Thrown away like an old shoe",
  "Well begun is half done",
  "It takes two to tango",
  "The pot calls the kettle black",
  "Life is full of ups and downs",
  "No news is good news",
  "A rolling stone gathers no moss",
  "Out of sight out of mind",
  "A little knowledge is dangerous",
  "Blood is thicker than water",
  "Icing on the cake",
  "Where there is a will there is a way",
  "Strike while the iron is hot",
  "Every minute seems like a thousand",
  "Knock at the door and it will be opened",
  "Love will find a way",
  "It never rains but it pours",
  "Easier said than done",
  "Many drops make a shower",
  "Like father like son",
  "A sound mind in a sound body",
  "As one sows so shall he reap",
  "Talk of the devil and you will hear the flutter of his wings",
  "Enter ye in at the strait gate",
  "No news is good news",
  "It is a piece of cake",
  "Slow and steady will win the game",
  "Birds of a feather flock together",
  "Even a worm will turn",
  "There is no such thing as a free lunch",
  "What is learned in the cradle is carried to the grave",
  "Blood is thicker than water",
  "To see is to believe",
];

module.exports = testSet;
