const testSet = [
  // test set A
  "greed has no limits",
  "stabbed in the back",
  "a rolling stone gathers no moss",
  "one man sows and another man reaps",
  "searching for a needle in a haystack",
  "do into others as you would have them into you",
  "finders keepers loser weepers",
  "be it ever so humble there is no place like home",
  "seize the day",
  "a rags to riches story",
  // test set B
  "pie in the sky",
  "one rotten apple spoils the barrel",
  "get angry at others for ones own mistakes",
  "do good and do not look back",
  "time and tide wait for no man",
  "if you laugh blessings will come your way",
  "talking to the wall",
  "do not count your chickens before they hatch",
  "charity begins at home",
  "he bit off more than he can chew",
  // test set C
  "empty vessels make the most sound",
  "every dog has his day",
  "casting pearls before swine",
  "a rat in a trap",
  "lets get to the point",
  "habit is a second nature",
  "a leopard can not change his spots",
  "everyone has a skeleton in the closet",
  "you have cried wolf too many times",
  "in one ear and out the other",
  "a journey of a thousand miles begines with a single step",
  "pride will have a fail",
  "mend the barn after the horse is stolen",
  "the grass is greener on the other side of the fence",
  "there is no place like home",
  "better late than never",
  "he that will steal a pin will steal an ox",
  "haste makes waste",
  "marry in haste repent at leisure",
  "adding insult to injury",
  "after the storm comes the calm",
  "face the music",
  "none but the brave deserves the fair",
  "a black hen lays a white egg",
  "can not get blood from a turnip",
  "shrouds have no pockets",
  "a man is known by the company he keeps",
  "to teach a fish how to swim",
  "nothing ventured nothing gained",
  "it is not good to listen to flattery",
  "no smoke without fire",
  "do not mount a dead horse",
  "starts off with a bang and ends with a whimper",
  "heaven helps those who help hemselves",
  "dead men tell no tales",
  "a friend in need is a friend indeed",
  "born is barn",
  "the sparrow near a school sings the primer",
  "bad workmen blame their tools",
  "a fool may talk but a wise man speaks",
];

module.exports = testSet;
